insert into users values (default, CURRENT_TIMESTAMP(), 'Rambo');
insert into users values (default, CURRENT_TIMESTAMP(), 'Billy');
insert into users values (default, CURRENT_TIMESTAMP(), 'Holly');
insert into users values (default, CURRENT_TIMESTAMP(), 'Van');
insert into users values (default, CURRENT_TIMESTAMP(), 'Vlad');
insert into users values (default, CURRENT_TIMESTAMP(), 'Andrii');
insert into users values (default, CURRENT_TIMESTAMP(), 'Jack');
insert into users values (default, CURRENT_TIMESTAMP(), 'Amogus');
insert into users values (default, CURRENT_TIMESTAMP(), 'Igor');
insert into users values (default, CURRENT_TIMESTAMP(), 'Egor');
insert into users values (default, CURRENT_TIMESTAMP(), 'Andrii');
insert into users values (default, CURRENT_TIMESTAMP(), 'Oleksandr');

insert into accounts values (default, CURRENT_TIMESTAMP(), 1700, 'Mono-bank', 1);
insert into accounts values (default, CURRENT_TIMESTAMP(), 4400, 'Private-bank', 1);
insert into accounts values (default, CURRENT_TIMESTAMP(), 3320, 'Binance', 1);
insert into accounts values (default, CURRENT_TIMESTAMP(), 5500, 'Mono-bank', 2);
insert into accounts values (default, CURRENT_TIMESTAMP(), 2200, 'Private-bank', 2);
insert into accounts values (default, CURRENT_TIMESTAMP(), 1400, 'Mono-bank', 3);
insert into accounts values (default, CURRENT_TIMESTAMP(), 6400, 'Sport-bank', 3);
insert into accounts values (default, CURRENT_TIMESTAMP(), 2400, 'BVR', 4);
insert into accounts values (default, CURRENT_TIMESTAMP(), 5430, 'Alfa-bank', 4);
insert into accounts values (default, CURRENT_TIMESTAMP(), 9320, 'Binance', 5);
insert into accounts values (default, CURRENT_TIMESTAMP(), 1367, 'Mono-bank', 5);
insert into accounts values (default, CURRENT_TIMESTAMP(), 1257, 'Private-bank', 5);